# Use root/example as user/password credentials
version: '3.1'

services:

  db: 
    container_name: "ServeWell"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    # (this is just an example, not intended to be a production configuration)
