# Use root/example as user/password credentials
version: '3'

services:

  db: 
    container_name: ServeWell
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    env_file:
      - .env
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    ports:
      - "3307:3306"


  # frontend:
  #   container_name: "Nextjs"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '${APP_PORT}:${APP_PORT}'
  #   volumes:
  #     - .:/app
  #     - ./package.json:/app/package.json
  #     - ./next.config.ts:/app/next.config.ts
  #     - ./next-env.d.ts:/app/next-env.d.ts
  #     - ./tsconfig.json:/app/tsconfig.json
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   env_file:
  #     - .env