# Use root/example as user/password credentials
version: '3.1'

services:

  db: 
    container_name: "ServeWell"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    # (this is just an example, not intended to be a production configuration)

  frontend:
    container_name: "Nextjs"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - ./package.json:/app/package.json
      - ./next.config.ts:/app/next.config.ts
      - ./next-env.d.ts:/app/next-env.d.ts
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - next-net

networks:
  next-net:
    driver: bridge